modelica/fmi-standard

- docs/2_2_common_schema.adoc
Change "fmi2ExitEventMode" to "fmi2EnterContinuousTimeMode"
> Fix #432: Definition of Model Variables (ModelVariables)

- headers/fmi2FunctionTypes.h
- headers/fmi2Functions.h
This PR adds parameter names to the function prototypes in the FMI headers to improve readability and allow IDEs to provide code completion.
Changes:
- add parameter names in fmi2FunctionTypes.h (as given in the specification document)
- add revision note
- replace non-ASCII copyright character w/ "(C)"
- fix indentations to align function parameters
@pmai did some research on this:
> Function Type Declarators with parameter names have been legal since ANSI C89/ISO C90, i.e. since declarators have been well-defined (see section 3.5.4.3 Function declarators, especially also the examples provided, together with sections 3.5.1/3.5.6). So any compilers having problems with this would not even be C88/90-compliant, and should be disregarded for FMI 3.0. If someone wants to use FMI3.0 with such …
> Add parameter names to function prototypes

- headers/fmi3FunctionTypes.h
size param for fmi3GetBinary was missing in #465
> Add missing parameter name for fmi3GetBinary size

- docs/0___preamble.adoc
- docs/2_1_common_api.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/3_3_model_exchange_schema.adoc
- docs/4_2_co-simulation_api.adoc
States are now referenced in bold face everywhere, and function names
are referenced without '(..)' added to some of the reference.
> Regularize state name and function name syntax

- docs/4_2_co-simulation_api.adoc
Port clarification from 2.0.1 (see #460 and #426).
> Fix #461 clarify valid calls after canceled step

- headers/fmi3FunctionTypes.h
- headers/fmi3Functions.h
- headers/fmi3TypesPlatform.h
- add new fmi3[U]Int{8,16,32,64} and fmi3Float variable types
- rename fmi3Boolean to fmi3Bool
- replace fmi3Integer with fmi3Int32
- replace fmi3Real with fmi3Double
- rename getters, setter and status functions accordingly
- remove "Real" from fmi3SetRealInputDerivatives and fmi3GetRealOutputDerivatives
> Add new numeric variable types to C API

- .travis.yml
- schema/fmi3AttributeGroups.xsd
- schema/fmi3Type.xsd
- schema/fmi3Variable.xsd
This change does not change the enumeration type to map to any of the
new types, but leaves it still implicitly mapped to fmi3Int32 (the successor
of the original fmi3Integer type).  Making the enumeration type map to
any of the new integer types would be useful addition, but would make
code quite a bit more complex, and also leave the schema definitions not
as expressive, since the valid ranges for min/max, etc. will depend on
an attribute.
> Initial support for numeric types in schemas

- LICENSE.txt
- README.adoc
- docs/0___preamble.adoc
- headers/fmi3FunctionTypes.h
- headers/fmi3Functions.h
- headers/fmi3TypesPlatform.h
- schema/fmi3Annotation.xsd
- schema/fmi3AttributeGroups.xsd
- schema/fmi3ModelDescription.xsd
- schema/fmi3Type.xsd
- schema/fmi3Unit.xsd
- schema/fmi3Variable.xsd
- schema/fmi3VariableDependency.xsd
to comply with FMI Project Rules v2.0 (2016-06-21)
- change license headers of *.h and *.xsd to "2-Clause BSD License"
- remove license extension
- add license LICENSE.txt
See also: #347, #423
> Change license headers to “2-Clause BSD License”

- headers/fmi3FunctionTypes.h
to allow importers to use the header files without modifications.
(solves #433)
> Remove const qualifiers in fmi3CallbackFunctions

- docs/2_3_fmu_distribution.adoc
and order versions from low to high
see also comments by @traversaro in #516
> Fix <abi_ver> in platform tuple for Visual Studio

- schema/fmi3Variable.xsd
Changes for the support of arrays of strings with whitespace according to 
https://github.com/modelica/fmi-standard/issues/513
> Support of arrays of strings with whitespace

- .gitignore
- docs/docinfo.html
- docs/fmi_specification.adoc
to allow compilation to other formats than HTML5
> Move auxiliary scripts to docinfo.html

- docs/2_1_common_api.adoc
> Remove type character when referencing variables

- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
see #528 
Converted schema section 2.2 of the array FCP doc file to adoc.
The changes are based on the last FMI3.0 word file (https://github.com/modelica/fmi-design/blob/master/FMI_3.0/FunctionalMockupInterface_3.0.docx)
some open problems:
- xml examples are missing
- ModelStructure/NumberOfEventIndicators is missing (only mentioned in api section 2.1)
...
> Feature/array description (#528)

- docs/2_1_common_api.adoc
error in the standard text section 2_1_common_api.adoc
void pointer is incorrect here. It should say (as above in other cases) "null" pointer
> correct minor NULL vs void pointer error

- docs/2_2_common_schema.adoc
to be consistent with the previous rule that only Float32/64 (previously Real)
can be "continuous"
> Use "discrete" as default variability for non-Float variables

- docs/2_2_common_schema.adoc
- docs/examples/build_configuration.xml
- schema/fmi3FMUType.xsd
- schema/fmi3ModelDescription.xsd
to avoid redundant BuildConfigurations and allow recreation of a
shared or static library from source that supports both Co-Simulation
AND Model Exchange. The build configuration is associated with the
respective interface type element via the "modelIdentifier" attribute.
> Move BuildConfiguration to fmiModelDescription

- CONTRIBUTING.adoc
- docs/1___overview.adoc
- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/2_3_fmu_distribution.adoc
- docs/2___common_concepts.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/3_3_model_exchange_schema.adoc
- docs/3___model_exchange.adoc
- docs/4_1_co-simulation_math.adoc
- docs/4_2_co-simulation_api.adoc
- docs/4_3_co-simulation_schema.adoc
- docs/4___co-simulation.adoc
- docs/5___literature.adoc
- docs/6___appendix.adoc
- headers/fmi3FunctionTypes.h
- apply one-sentence-per-line rule
- add underscores to every italic line
- remove excess line breaks
- fix double quotes vs. backticks
- add xrefs to literature
> Fix formatting

- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_1_co-simulation_math.adoc
- docs/4_2_co-simulation_api.adoc
- docs/6___appendix.adoc
Changes include:
- Formatting to bold using **
- capitalization
- CamelCase to Space Separated
- sometimes mode was capitalized when not a state name
Please also consider and comment issue #718.
> Fmi3 state names #705

- docs/2_2_common_schema.adoc
Also clarifies and corrects recommendations for floating point significant digits to be in line with IEEE 754.
> Add missing XML types for new variable types #697

- docs/2_2_common_schema.adoc
The integer type of start and valueReference attributes of Dimensions are expected to be the same, xs:unsignedInt, ie. fmi3Uint32.
Fixes #733
> Clarify the integer type of Dimensions' start attributes

- docs/2_1_common_api.adoc
- docs/4_1_co-simulation_math.adoc
rephrase "communication interval" into "two consecutive communication points" because the term "communication interval" is not defined.
> rephrase-communication-interval

- CONTRIBUTING.adoc
- docs/examples/c-code/VanDerPol/sources/fmi3Functions.c
- headers/fmi3FunctionTypes.h
Missing const for input parameters
> Fixed constness of parameters in fmi3SetIntervalDecimal and fmi3SetIntervalFraction

- docs/2_1_common_api.adoc
Compared to FMI 2.0 in 3.0 the valueReference handle now identifies a
variable uniquely. In FMI 2.0 only valueReference and type were globally
unique.
> The valueReference handle is globally unique in FMI 3.0

- docs/2_1_common_api.adoc
In a static linked library the FMI function name is prefixed with the
modelIdentifier.
> Fixed static linked library function call.

- docs/2_1_common_api.adoc
The variable names in the document for getting dependencies are
different than the names in the header files.
> Fixed variable names for getting dependencies

- headers/fmi3FunctionTypes.h
Array input parmeters use the notion "const TYPE varname[]" in FMI not
"const TYPE *varname".
> Fixed array input parameter in C-API

- docs/2_2_common_schema.adoc
- docs/4_2_co-simulation_api.adoc
I compared all &#8800; signs from FMI 2.0.1 with the current 3.0 master and found two occurances that were wrong.
fixing #735
> fixing two not-equal signs compared to FMI 2.0.1

- docs/2_2_common_schema.adoc
Their is no "Dimensions" element with child "Dimension" elements for each
dimension of an array variable.
The "Dimension" elements are just a sequence of elements without an
seperate parent element.
> Fixed specification text to map xsd files and examples.

- docs/2_1_common_api.adoc
However, this parameter is not noted in the description (for getter
functions the sizes paraemters is noted).
> C-API setter function may also have an sizes parameters.

- docs/2_1_common_api.adoc
FMI 3.0 has arrays as "native" variables. Structures are still flattend
to single variables.
> Arrays are no longer flattend to variables.

- docs/6___appendix.adoc
... from glossary.
The value reference is clearly defined in 2.2.10. 
Why should we define it also in the glossary?
The current definition in the glossary reflected the non-uniqueness of FMI 2.0.
Fixing also https://github.com/modelica/fmi-standard/issues/522
> remove double and contradicting definition of value reference 

- docs/docinfo.html
- docs/index.adoc
With this pull-request the TOC in the left side will show up to 5 levels (max according to asciidoctor https://asciidoctor.org/docs/user-manual/#table-of-contents-summary.
Additionally, the numbers will be shown in the text.
@andreas-junghanns you assigned yourself to this - I hope it is okay, that I created this pull-request.
> Fixes #650. Adds explicit numbering html.

- docs/2_2_common_schema.adoc
The section about structured variable naming describes the flattening of
arrays using the [...] syntax of structure variable naming.
Clarify that this flattening is possible but no longer required for leaf
node variables of the hierarchy when the new array are used.
> Some clarification of array variables regarding structured variable naming

- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/4_3_co-simulation_schema.adoc
Adapted the clock variable names in the document according the header
files. Clock activitiy is also not given by fmi3True/fmi3False but by
fmi3ClockActive/fmi3ClockInactive.
> Fixed clock variable and enumeration names.

- docs/2_2_common_schema.adoc
Precisely define how PNG and SVG images are mapped to the coordinate definition of terminals: For PNG just the corners are used for SVG the viewport corners are used.
> Define the mapping from terminal coordinates to image coordinates.

- docs/2_2_common_schema.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_1_basic_co-simulation_math.adoc
- docs/5_2_hybrid_co-simulation_api.adoc
- docs/8___appendix.adoc
Simple adding '-' to "super-dense time" wherever missing
> Add hyphen to super-dense time

- docs/1___overview.adoc
- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/3_2_model_exchange_api.adoc
fixing #741 
Getting the number of states and event indicators cannot be done
consistently since every state is also present as a variable but event
indicators are not.
Now a clear defintion is given how the static number of states/events
can be get without using C-API function calls and also how to get the
dependent structural parameter the number of states/events depends on.
> Clarify the number of states/event indicators (#741)

- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/examples/c-code/VanDerPol/modelDescription.xml
- schema/fmi3ModelDescription.xsd
The current FMI 3.0 has a well defined variable (including a
valueReference) for all types of values, including states, state
derivatives and the independent variable (time), but not for event
indicators.
This commit fixes this.
Event indicators are listed now in ModelStructure and have therefore a
corresponding variable with a valueReference. Event indicators can be of
causality local and output (as states).
The c-API function for getting event indicators keep the same but
fmi3GetFloat64 can now also be used.
> Define event indicators as variables (#587)

- docs/2_2_common_schema.adoc
Parameters and tunable parameters are NOT knowns in continous time mode,
event mode and cosimulation step mode. This would imply that derivatives
wrt parameters are possible in these modes.
Their is a working group for derivatives wrt parameters (for
optimization and sensitivity analysis) but this does not go into 3.0.
> Clarify that parameters are not knowns in continous time mode

- docs/2_2_common_schema.adoc
- docs/2_3_fmu_distribution.adoc
- schema/fmi3ModelDescription.xsd
A clear definition of the path of the attributes iconSource_PNG and
iconSource_SVG were missing.
> Define the path of FMU and terminal icons.

- docs/4_2_basic_co-simulation_api.adoc
- docs/6_2_scheduled_co-simulation_api.adoc
Minor spelling issue: There was both "usable" and "useable" used in subsequent comments.
> Prefer usable over useable

- docs/2_2_common_schema.adoc
inflow/outflow can only be used for scalars which sum up to zero. Other
quantities which also sum up to zero (at connection points) are not
covered by inflow/output.
This is now stated as non-nominative text.
> Clarify inflow/outflow in terminals #772

- docs/2_1_common_api.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_2_basic_co-simulation_api.adoc
Someone already dropped some of the [] but not consistently. I tried to catch the rest.
> Remove [] from argument names

- docs/3_2_model_exchange_api.adoc
- docs/4_2_basic_co-simulation_api.adoc
- docs/5_2_hybrid_co-simulation_api.adoc
- docs/6_2_scheduled_co-simulation_api.adoc
These are a few minor changes all trying to unify the 4 state machine description formats and texts
> Unify headers and descriptions of state machines

- docs/2_2_common_schema.adoc
- schema/fmi3Terminal.xsd
memberName is optional for sequence but not for plug and bus,
remove "name/sequence-based",
fix alias handling
> All sequence related changes

- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/2_4_common_co-simulation.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_2_basic_co-simulation_api.adoc
- docs/4_3_basic_co-simulation_schema.adoc
- docs/5_2_hybrid_co-simulation_api.adoc
This addresses #933.
I am not sure this really helps to improve readability.
You are still left wondering in a few places where the XML attribute is not clearly understandable as such.
Also: I have seen strange math not-equals mixed in.
I will also fix those in a next change set.
> Fix C-style == and != signs

- schema/fmi3BuildDescription.xsd
- schema/fmi3ModelDescription.xsd
- schema/fmi3Terminal.xsd
- schema/fmi3Type.xsd
- schema/fmi3Variable.xsd
If we want all attributes to be there, even with default values, we should be consistent and always have them everywhere. I think removing default settings is cleaner.
> Remove XSD attributes with default values

- docs/2_1_common_api.adoc
Fixing #931 , replacing #987, which aimed at FMI 3.0
@andreas-junghanns : In contrast do https://github.com/modelica/fmi-standard/pull/987/commits/a89f05ea0c5e18bae071703409fb85ace4863c16 this shall be non-normative, right?
when you approve this, I will also include it in the FMI 2.0.2 word document.
> Discourage use of memory callbacks in FMI 2.0.2

- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/3_3_model_exchange_schema.adoc
- docs/4_3_basic_co-simulation_schema.adoc
- docs/5_3_hybrid_co-simulation_schema.adoc
- docs/6_3_scheduled_co-simulation_schema.adoc
- schema/fmi3InterfaceType.xsd
resolves #1017 
additionally fixes the missing description of providesAdjointDerivative schema description for ME and BCS listed in #1018, #1019
> change partial derivative capabilities to plural + list them in schema description

- docs/1___overview.adoc
- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/2_4_common_co-simulation.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_1_basic_co-simulation_math.adoc
- docs/4_2_basic_co-simulation_api.adoc
- docs/4_3_basic_co-simulation_schema.adoc
- docs/5_2_hybrid_co-simulation_api.adoc
This is work in progress to close https://github.com/modelica/fmi-standard/issues/795
So far, I've tried to make less ambiguous references like:
- "below"
- "above"
- "following"
I've also numbered a few figures and tables, and found other figure that had an absolute number on them (Fig 12 in the master branch).
The reason these "loose" references are so bad is that even if they start rigorous (for instance, when the word "below" actually shows up in the line right before the object referred to), as new content gets added, they become drift away from the object, until it becomes really hard to figure out what "below" refers to...
Still do to:
> Avoid ambiguous references to code, figures, and tables.

- schema/fmi3Variable.xsd
This addresses the breakage in the enumeration variable definitions identified in #1034, as well as changing start value lists to use the itemType instead of a restricted type, as identified in #1033, as well as some other minor cleanups.
Nested attributegroups also mentioned in #1033 are not that easy to do away with without introducing a bit of duplication, so whether to go down this route, or rather suggest a simple xslt transformation for the schema for implementers so constrained, is something to be discussed in the #1033 issue going forward, but this PR contains the easy fixes, as far as I can tell. Fixes #1034.
> Fix XML schema mechanics around variables

- docs/2_2_common_schema.adoc
.... as the FMU cannot know, if a variable is used as an iteration of an algebraic loop, so we cannot claim this in normative text.
> fix description of initial==approx

- docs/5_2_hybrid_co-simulation_api.adoc
Resolves  #665 
Initially I thought this chapter had a extraneous part that needed to be moved to its proper place. But I think the idea of the chapter is rather to explain the early-return and event-handling mechanisms. I tried to fix this with this PR
> Reword Early Return and Event handling description

- docs/2_2_common_schema.adoc
Resolves https://github.com/modelica/fmi-standard/issues/1005
- The master here is interpreted as an input clock (we think that's the intention)
- We removed the sentence "If <<causality>> = <<input>> the value for <<initial>> has to be set to <<exact>>" because the same information is specified in the table below.
The fixes are done by me, @IZacharias , and @MBlesken .
> Issue 1005: Clarify the meaning of master clock.

- schema/fmi3AttributeGroups.xsd
- schema/fmi3Type.xsd
- schema/fmi3Variable.xsd
Resolves #1033 
This makes the schema more useful to various tools that are not able to deal with nested attributeGroups in sane ways. It is a schema internal change and does not affect XML instances.
> Avoid nested attribute groups (fix #1033)

- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
- docs/2_4_common_co-simulation.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_1_basic_co-simulation_math.adoc
- docs/4_2_basic_co-simulation_api.adoc
- docs/6_2_scheduled_co-simulation_api.adoc
- docs/8___appendix.adoc
Resolves #808 
Taking into account notes from the Berlin FMI Design meeting https://github.com/modelica/fmi-design/blob/master/Meetings/2020-02-25-FMI-Design-Berlin/minutes.adoc#detailed-discussions-and-polls 
Please review, comment and improve (maintainers are welcome to directly commit)
Do we need a change in an xsd making sure to have exactly one independent variable?
> make independent variable mandatory in xml and add references to indepent 

- docs/4_1_co-simulation_math.adoc
- docs/4_2_co-simulation_api.adoc
- docs/4___co-simulation.adoc
Resolves #1050 
(I have not renamed the clock activiation times to c_i as this seems misleading to "constants"; so t_i is used both for communication timesteps in CS and clock activation times for clocks. As these different meanings are used in different chapters, it is clear from the context what t_i means. If someone disgrees, please improve ....)
> Replace tc_i with t_o and hc_i with h_i

- docs/1___overview.adoc
- docs/2_1_common_api.adoc
- docs/2_2_common_schema.adoc
This was a complete mess: paragraphs ripped apart, descriptions in the wrong places and orders, duplicate paragraphs, ...
Since I did not edit content, just moved and sorted stuff, I will merge in 24h if you do not stop me.
> Fix terminal description

- docs/4_1_co-simulation_math.adoc
- docs/4___co-simulation.adoc
Fixes https://github.com/modelica/fmi-standard/issues/613
This leaves out the part where the intermediate inputs can be set with zero delay. I think we don't yet have the mathematical machinery to describe this.
> Fix issue 613

- docs/1___overview.adoc
Removes the inconsistent example for usage of 1-based indices mentioned in https://github.com/modelica/fmi-standard/issues/1128#issuecomment-680116448 (variable index is no longer present in FMI 3.0)
If some has a better example, please commit
> Remove reference to variable index in example for array convention

- docs/3_1_model_exchange_math.adoc
This addresses a point of #1015 : 
The comment on how to implement synchronous systems with FMI should point to the new clocks feature in the first place and only additionally describe how to implement such a behaviour "manually"
> update comment on synchronous systems to FMI 3.0

- docs/2_2_common_schema.adoc
- docs/3_2_model_exchange_api.adoc
This still misses:
- addition of ClockedState to ModelStructure (to list dependencies)
- renaming of Derivative to StateDerivative (to differentiate to normal variable derivatives)
This should be discussed tomorrow at the design meeting.
> Explain local variables

- docs/2_5_fmu_distribution.adoc
Resolves #1226 
by moving  "Supporting Multiple Interface Types in one FMU" one level up (and out of the extra directory section)
> Move "Supporting Multiple Interface Types in one FMU" out of "extra directory"

- schema/fmi3Variable.xsd
The `start `attribute for strings became an element (`Start`) in this PR #523. This is fine and was discussed several times.
However, in the current xsd the `Start `element is mandatory.
Currently xsd validation fails for a String variable like this:
```
<String name="StringOut" valueReference="13" causality="output" variability="tunable">
<Dimension valueReference="0"/>
<Dimension valueReference="1"/>
</String>
```
This PR fixes the xsd to allow such `String` variables without `Start` elements.
> Allow String variables without Start elements

- schema/fmi3Variable.xsd
Remove schema default value for variability attribute of variables, since the actual default (continuous vs. discrete) depends on the variable type (i.e. float vs. other types), and hence needs to be handled by the application, not the XML parser. Fixes #1243.
The only alternative in XML Schema 1.0 would be to drop the attribute from the base type and introduce it some level below that, which seems suboptimal.
> Remove schema default for variability (fix #1243)

- docs/2_2_common_schema.adoc
Resolves #1266
backport correction for relative quantity to 2.0.x. 
After merging, I will update the 2.0.2. word document
> Backport relative quantity correction to FMI 2.0.2

- docs/2_6_source_code.adoc
- schema/fmi3BuildDescription.xsd
Hello. The motivation to add a name attribute to a soucefileset is the following use case: A consumer wants to compile a source file set and create a library for which he needs to choose a name. If provided by the source file set the name attribute can be used to name the library. I would like to invite everyone to express their opinion on this small extension and hopefully approve the idea. Thank you.
> Add Name to sourcefileset

- headers/fmi2FunctionTypes.h
Checklist
Add your [meaningful description](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#bug-reports) here and reference any related issues with `#<issue>`.
> Add missing parameter name "serializedState" in fmi2SerializeFMUstate()

- docs/2_5_fmu_distribution.adoc
This also generalizes the MSVC version for `abi_ver` = 141.
> Add ABI version for VS 2019

- docs/2_3_common_states.adoc
Fix link to "state" by inserting a newline
(for #1272 generation and upload of generated html is not working)
> add newline to fix link to states

- docs/2_3_common_states.adoc
- docs/2_5_fmu_distribution.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_2_co-simulation_api.adoc
- docs/5_2_scheduled_execution_api.adoc
a proposol to fix  the topic of this comment: https://github.com/modelica/fmi-standard/pull/1272#discussion_r573206441 
(I falsely read the "equations and actions" tables to suggest a specfic calling order of the associated API functions.)
> Clarify that in "equations and actions" tables there is no order

- docs/2_5_fmu_distribution.adoc
This PR fixes two tiny issues on the FMU compression:
* The compression property (as for example returned by `unzip -Zsvh HybridVehicle.fmu`) is called `deflated`.
* The compression method is not a per-archive property, but a per-file property.
Additionally, it is not clear which zlib tool is meant, since usually zlib is a library (see https://en.wikipedia.org/wiki/Zlib).
> Fix compression method name `deflate` -> `deflated`

- README.adoc
- docs/0___preamble.adoc
- docs/1___overview.adoc
- docs/2___common_concepts.adoc
- docs/7___appendix.adoc
- docs/index.adoc
Out logo uses "Functional Mock-Up Interface".
The web page almost always uses "Functional Mock-up Interface" in the text.
Do we want to use the logo way in 3.0?
This PR has the required changes.
> Turn up into Up for Functional Mock-Up

- docs/3_2_model_exchange_api.adoc
> allow getNominalsOfContinuous stats in intialization model in FMI 2.0.3, backport of #1284

- headers/fmi3PlatformTypes.h
Given that we already depend on the C99 integer types for our integer
types, we might as well switch to use the C99 _Bool type and integer
types for all other typedefs to make the interface ABI more stable.
This reflects the discussions in the design meeting on 2021-02-19
Checklist
See also PR #1102 which started the discussion.
> Use C99 int/bool types for all types

- docs/2_4_common_schema.adoc
The current spec still mentions that the variable elements of <ModelVariables> are an ordered set.
I think this is not necessary anymore and even confusing for the reader.
The ordering was only important when indices were used and got obsolete after we switched to use valueReferences.
> Don't mention that variables are an ordered set

- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
As discussed concerning in last design meeting the intermediateUpdateTime is not relevant in SE. @andreas-junghanns, @chrbertsch please have a look. FYI: @IZacharias Closes #1308
> intermediateUpdateTime in SE

- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- docs/2_4_common_schema.adoc
- docs/3_2_model_exchange_api.adoc
- docs/examples/model_exchange.xml
- docs/examples/model_structure_example1.xml
- docs/examples/model_structure_example4.xml
- headers/fmi3FunctionTypes.h
- headers/fmi3Functions.h
- schema/fmi3ModelDescription.xsd
to clearly distinguish the different types of derivatives in 
- fmi3GetContinuousStateDerivatives()
- fmi3GetOutputDerivatives()
- fmi3GetDirectionalDerivative()
- fmi3GetAdjointDerivative()
and
<ContinuousStateDerivative />
fixes #1343
> Unify naming of "continuous states" and "derivatives" in API and XML

- CONTRIBUTING.adoc
- docs/1___overview.adoc
- docs/2_1_common_math.adoc
- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- docs/2_4_common_schema.adoc
- docs/3_2_model_exchange_api.adoc
- docs/3___model_exchange.adoc
- docs/4_4_co-simulation_schema.adoc
- docs/4___co-simulation.adoc
- docs/5_1_scheduled_execution_math.adoc
- docs/5_2_scheduled_execution_api.adoc
- docs/5_3_scheduled_execution_example.adoc
- docs/5_4_scheduled_execution_schema.adoc
- docs/7___appendix.adoc
- headers/fmi3FunctionTypes.h
- schema/fmi3Variable.xsd
> Clean up Clocks API and schema

- docs/7___appendix.adoc
... as it is not used in the spec.  (and was mis-spelled as tick relationshipt :-) )
> remove tick relationship from glossary

- docs/2_5_fmu_distribution.adoc
- docs/examples/build_description_simple.xml
This will avoid duplicate object names and symbols when compiling and linking multiple source code FMUs into the same binary, e.g. for a HiL application.
> Recommend file name and static symbols for source code FMUs

- docs/6___literature.adoc
- docs/7___appendix.adoc
... as the glossary was almost completely re-written and the cited Modelisar glossary is not publicly available. It is anyway clear that FMI stems from the Modelisar ITEA project.
> Remove reference to Modelisar glossary 

- docs/2_5_fmu_distribution.adoc
The example tuples in 2.5.1.4.2. had the wrong order.
> fix order in example tuples

- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- docs/2_4_common_schema.adoc
Introduces clocked states when clocked variables are introduced.
Removes the sample-and-hold semantics for clocked variables.
Explains that clocked states can be optionally declared in Initial Unknowns to be initialized.
This PR closes https://github.com/modelica/fmi-standard/issues/1402
Addresses items 2,3, and 5, of the summary here: https://github.com/modelica/fmi-standard/issues/1407#issuecomment-819509403
@andreas-junghanns can you add the content to address item 1 of  [the summary](https://github.com/modelica/fmi-standard/issues/1407#issuecomment-819509403)? I was not able to figure out where to describe it.
> Introduces clocked states when clocked variables are introduced.

- docs/2_3_common_states.adoc
- docs/6___literature.adoc
- docs/7___appendix.adoc
Renamed "Transmission Line Method" to "Transmission Line Modeling", which is the most commonly used name for the method.
Also added anchors and a reference.
> Rename Transmission Line Method to Transmission Line Modeling

- docs/5_1_scheduled_execution_math.adoc
DRAFT. Fixing a false remark on output clocks by using a new formulation about countdown Cloks from https://github.com/chrbertsch/fmi3pap. Compare chrbertsch/fmi3paper#4 (comment)
> Fix SE concepts intro

- headers/fmi3Functions.h
The function defines in fmi3Functions.h for the newly introduced clock shift accessor functions were missing.
> Add missing function defines for shift accessors

- docs/2_2_common_mechanisms.adoc
- docs/5_1_scheduled_execution_math.adoc
- docs/5_2_scheduled_execution_api.adoc
- docs/7___appendix.adoc
link to issue #1421
I noted that "clock activation" and "clock tick" seemed to be used synonymously.
If you agree to this issue, then clock ticks and clock activations become two different things, hence my changes "clock activation" -> "clock tick" when referring to input clocks.
> Remove reference to input clock activations from SE text

- .circleci/generate_figures.ps1
- docs/2_4_common_schema.adoc
This small change helps prevent inconsistencies like https://github.com/modelica/fmi-standard/issues/1454
> Add check empty figure in generate_figures.ps1 script

- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- headers/fmi3FunctionTypes.h
- headers/fmi3PlatformTypes.h
This shall resolve issue #1450.
It enables the evaluation of output equations f_event independently
from state equations f_state with the fmi3Clock value fmi3ClockSubactive.
This is particularly needed for model exchange.
> Introduce f_disc to separate discrete state equations from f_event

- headers/fmi3FunctionTypes.h
- headers/fmi3Functions.h
and align function order with fmi3FunctionTypes.h
fixes #1480 and #1481
> Add missing function defintions in fmi3Functions.h

- docs/2_5_fmu_distribution.adoc
fixes #1477
Update 1 after my discussion with @andreas-junghanns:
This proposal is by no means an invitation to link dynamically, but to legalize the large number of FMUs that are doing it already (for various reasons) and will continue to do it. Not allowing  it (even though it is clearly discouraged) will e.g. lead to the exclusion of a large number of FMUs from the Cross-Check, because they are clearly illegal according to the current specification (see also https://github.com/modelica/fmi-cross-check/issues/57).
Update 2: 
At least on Windows we have to distinguish between two types of dependencies on external DLLs:
1. Load time dependencies that are declared in the `<modelIdentifier>.dll`. These can be determined before calling `LoadLibrary()` and an error message can be displayed to …
> Relax requirement for including dependencies

- docs/1___overview.adoc
Checklist
N/A [Re-generated schema figures](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#changing-the-xsd-schemas).
The sentence prior to the change did not make sense:
> All lists defined in the fmi3ModelDescription.xsd XML schema file have a string attribute name **to a list element**.
I think the `to a list element` comes from an earlier version of the senctence which is not required anymore. I suggest this version of the sentence:
> All lists defined in the fmi3ModelDescription.xsd XML schema file have a string attribute called name.
> fixed sentence about list attribute name

- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- docs/2_4_common_schema.adoc
- docs/5_1_scheduled_execution_math.adoc
- docs/examples/snippets.c
- headers/fmi3FunctionTypes.h
The specification is unclear about the concrete time of a countdown clock tick.
Across the spec there are described two contradictory point of views:
1. A countdown clock ticks while a model partition is being executed, i.e. the clock already has ticked when intermediate update is invoked.
2. A model partition can only signal that a countdown clock is about to tick. The actual ticking takes place after the provided interval is run out.
Here are some quotes that state the first variant:
- Section 2.2.9.4:
>The FMU may request to schedule another model partition even while currently a model partition is being executed. countdown Clocks can tick at any time during the execution of any model partition. The FMU signals their ticking by calling fmi3CallbackIntermediateUpdate with argument …
> Clarify countdown clock ticks

- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- docs/5_1_scheduled_execution_math.adoc
- docs/5_2_scheduled_execution_api.adoc
- docs/5_3_scheduled_execution_example.adoc
- docs/examples/snippets.c
- headers/fmi3FunctionTypes.h
This pull request includes following changes:
1. Some clarifications on the handling of intervalUnchanged and intervalNotYetKnown
2. Some restructuring of the SE code example
3. Adding getInterval to allowed functions of Clock Activation Mode
4. Removing of redundant parameters of clock specific getter and setter functions that are relicts of when clocks were not restricted to be scalars (e.g. nIntervals in getInterval). 
I'm not sure if the redundant parameter maybe was kept intentionally for some reasons. However, it is probably confusing for the reader to have two parameters for the same value. An alternative would be to state explicitly that nValueReferences and nIntervals always have the same value. Not very nice, though.
> Some changes regarding intervalQualifier and getInterval

- docs/5_1_scheduled_execution_math.adoc
I think I found all changes of #1546 that have unwillingly be reverted in #1560 on November 24th. It was just a small part of the Preemption section in SE.
@andreas-junghanns would you please review. FYI @PTaeuberDS @klausschuch
> Revert changes in Preemption Section

- docs/1___overview.adoc
- docs/2_2_common_mechanisms.adoc
- docs/5_4_scheduled_execution_schema.adoc
Since the term _task_ is usually raising questions and discussions I replaced the term in a couple more spots. Everyone is welcome to review.
> Remove the term task

- docs/7___appendix.adoc
@andreas-junghanns maybe you can adjust this attempt when reviewing. My questions are:
* Why was the definition for schedule execution not named _FMI for_ scheduled execution?
* Why was " It consists of the model description and the C API." only stated for ME?
* Is SE "One of the MODELISAR Functional Mock-up Interface types.", too? (Please add if applicable.)
> Align definitions for FMI types 

- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- docs/2_4_common_schema.adoc
Fixes https://github.com/modelica/fmi-standard/issues/1622
Fixes https://github.com/modelica/fmi-standard/issues/1620
> Clarify clock dependencies requirements

- docs/examples/scheduled_execution.xml
Reacting to VDMCheck3 check 
_fmi-standard/docs/examples> VDMCheck3.sh scheduled_execution.xml  
Checking XML 
1023: 2.2.9 Outputs section does not match output variables at XML:31 
1028: 2.2.9 InitialUnknowns must include refs: {2, 4} 
Errors found._
>1023: 2.2.9 Outputs section does not match output variables at XML:31 
I adjusted the ModelStructure.
> 1028: 2.2.9 InitialUnknowns must include refs: {2, 4} 
The question arises whether the _clocks_ attribute of the out clock should be removed. The standard does not forbid to leave it. Note that depending on whether the clock attribute is defined or is not defined the output clock is a clocked or not a clocked variable. If it is a clocked variable it would have to be listed as InitialUnknown ("are not clocked variables and have causality = …
> VDMCheck3 on SE xml

- docs/2_1_common_math.adoc
- docs/2_2_common_mechanisms.adoc
- docs/2_3_common_states.adoc
- docs/2_4_common_schema.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_1_co-simulation_math.adoc
- docs/4_2_co-simulation_api.adoc
- docs/4_4_co-simulation_schema.adoc
- docs/5_1_scheduled_execution_math.adoc
- docs/5_2_scheduled_execution_api.adoc
This now makes the use of `=` consistent.
Note: an argument for the single `=` is that it in all circumstances this now reads the same for importer and FMU.
When using `==`, it is really only right for the side to check the conditions, the other side needs to meet that condition and why would you write it as `==`?
So after reading through the changes, I am more convinced than before that single `=` is the better solution.
> Change == to = in text and insert spaces around =

- docs/2_2_common_mechanisms.adoc
- headers/fmi3FunctionTypes.h
> Remove redundant "shifts" and "intervals" prefixes

- docs/2_2_common_mechanisms.adoc
- docs/2_4_common_schema.adoc
Clarify that dependency is direct /related to partialDerivative, non normative text explaining dependency on independent variable
> Improve text for dependency

- docs/2_2_common_mechanisms.adoc
- headers/fmi3Functions.h
As discussed in the last fmi design meeting, this adds functionality to the standard fmi3Functions.h header to override the FMI3_FUNCTION_PREFIX easily from the outside by defining the `FMI3_OVERRIDE_FUNCTION_PREFIX` preprocessor macro.
> Add override functionality for FMI3_FUNCTION_PREFIX

- docs/2_2_common_mechanisms.adoc
As agreed during today´s FMI design meeting, I created this PR to explicitly define local clocks and their restrictions.
> Add local clocks to clocks table and definitions

- docs/2_3_common_states.adoc
- docs/3_1_model_exchange_math.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_2_co-simulation_api.adoc
- docs/7___appendix.adoc
- headers/fmi3FunctionTypes.h
This should clarify and correct the presentation of fmi3EnterEventMode for CS.
It narrows down the allowable values for unused arguments, and corrects errors in both descriptions with regards to CS use.
> Add full description for CS version of fmi3EnterEventMode

- docs/3_1_model_exchange_math.adoc
Checklist
* [ x] Used a [personal fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) of the repository to propose changes.
* [ x] [Linted the documents](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#building-the-specification-document).
As I mentioned in #1739 I think we should really make it clear that it's the FMU that should add the hysteresis and not the importing tool.
> Spell out that it's the FMU that should add a hysteresis

- docs/2_3_common_states.adoc
Stated at function enterEventMode, should be event that is entered in call to enterEventMode
see
https://github.com/modelica/fmi-standard/pull/1744#discussion_r856142585
> Modify sentence of when time event should be handled

- docs/7___appendix.adoc
resolves #1758  (tools participating in XC): Please check
Fix Comments by @MBlesken  in https://github.com/modelica/fmi-standard/issues/1737#issuecomment-1108361917 .
@MBlesken : "Maybe separate country followed by next name by more than just a blank": I do not find this. Wasn't this fixed already? Or could you please create a PR?
Company names are still not uniform (with or w/o "GmbH")
> Fix contrib

- docs/7___appendix.adoc
I'd prefer to remove my former affiliation "TraceTronic GmbH" since neither TraceTronic as company nor myself was engaged at FMI design meetings when I was with TraceTronic. Better to have it as "previously at ESI Group", which holds for all (future) times.
See also https://doc.modelica.org/Modelica%204.0.0/Resources/helpDymola/Modelica_UsersGuide.html#Modelica.UsersGuide.Contact (for the (former) contributors of MSL).
Checklist
Fix for #1757.
> Fix sorting and update former affiliation

- docs/2_3_fmu_distribution.adoc
for platforms other than {darwin|linux|win}{32|64}
fixes #1764
> Use FMI 3.0 platform tuples

- docs/2_4_common_schema.adoc
Draft to fix #1799 on FMI3 side according to Pierre's and Christian S's proposal.
> Clarification for matching

- docs/2_1_common_math.adoc
resolves #1830 
as it was intentinally disallowed in FMI 3.0 to get output derivatives in SE, see e.g. https://github.com/modelica/fmi-standard/issues/1587
> Bugfix: dissalow output derivatives in SE

- schema/fmi3Variable.xsd
Fixes #1837, where enumerations had no allowed Annotations and Dimension elements due to the content not being repeated in the restriction for mandatorily typed variables, i.e. enumerations.
> Fix missing content in XML schema for enums

- docs/2_4_common_schema.adoc
resolves #1835
by deifing default variabiliy as "discrete" for varaibles of type other than float32 or float64
> Define default variability

- docs/4_2_co-simulation_api.adoc
Added a comment that this should not be used if the step terminated early due to an error to resolve #1844
> Clarify earlyReturn from fmi3DoStep

- docs/2_5_fmu_distribution.adoc
New apptempt to fix #1822 as discussed in todays design meeting. See https://github.com/modelica/fmi-standard/pull/1832#issuecomment-1410453308
> Clarify use of binaries and resources folder

- docs/2_6_versioning_layered_standards.adoc
- docs/examples/fmi_ls_manifest_example.xml
- docs/examples/fmi_ls_manifest_minimal_example.xml
This provides the initial proposal for the FMI layered standard manifest information that is suggested for layered standards to support.
Modifications might be needed to make the whole added part non-normative, and we might want to also provide a schema that allows checking of those attributes.
This is against the 3.0.x branch to ease discussion/merger, backmerge to main can be performed afterwards.
> Initial proposal for FMI layered standard manifest

- docs/2_6_versioning_layered_standards.adoc
- docs/examples/fmi_ls_manifest_example.xml
- docs/examples/fmi_ls_manifest_example_schema.xsd
- docs/examples/fmi_ls_manifest_minimal_example.xml
- schema/fmi3LSManifest.xsd
- schema/fmi3LayeredStandardManifest.xsd
This adds a schema for the manifest attributes and the default minimal manifest, and enhances the examples to showcase that to some extent.
> Enhance ls manifest description with schema

- docs/2_2_common_mechanisms.adoc
Resolves #1877 
Other API functions that use concatenated (serialized) array varaibles to be checked.
> Clarify array concat

- docs/2_3_common_states.adoc
- docs/2_4_common_schema.adoc
> Clarify intermediate update

- docs/2_2_common_mechanisms.adoc
- docs/2_4_common_schema.adoc
- docs/3_2_model_exchange_api.adoc
- docs/4_1_co-simulation_math.adoc
As in the comments on the merged PR #1882 there were some remarks on duplicatation of wording, this is an attempt to simplify it by providing all information in the serialization paragraph and referencing it.
> put serialization info at one place

- docs/2_4_common_schema.adoc
The referenced content is found in the attribute details table.
> Fixing reference to incorrect table

- docs/2_2_common_mechanisms.adoc
- docs/2_4_common_schema.adoc
> Clarify the information flow of clocks

- docs/2_3_common_states.adoc
Fixes #1916 
Removes the contradicting statement that aperiodic Clocks are not allowed to be activated more than once per Event Mode.
> Clarify multiple Clock ticks per Event Mode for different Clock types

- docs/4_1_co-simulation_math.adoc
The section "4.1.2. Getting Derivatives of Continuous Outputs" describing the fmi3GetOutputDerivatives function is broken due to a missing >. This PR fixes it.
> Fix the fmi3GetOutputDerivatives description

- docs/3_2_model_exchange_api.adoc
via fmi3SetFloat64()
fixes #1952
> Allow setting continuous states in Continuous Time Mode

- docs/2_4_common_schema.adoc
- docs/7___appendix.adoc
> Add definition of reinitialization to glossary

- docs/2_3_common_states.adoc
> Allow setting continuous states in Event Mode if reinit = false

- docs/2_4_common_schema.adoc
> Clarify meaning of DefaultExperiment.stepSize for Model Exchange

- docs/1___overview.adoc
> Clarify when to use Scheduled Execution

- docs/2_4_common_schema.adoc
Fixing https://github.com/modelica/fmi-standard/issues/1942
> Introduce matching rule 'none'

- docs/2_1_common_api.adoc
> Describe that fmi2Reset can be called in case of fmi2Error

- docs/2_4_common_schema.adoc
- docs/2_5_fmu_distribution.adoc
- docs/2_6_versioning_layered_standards.adoc
- docs/7___appendix.adoc
resolves #1967  
resolves #1943
> Unify description of reverse domain name notation, strong recommendation to use it for variable and terminal kinds

- docs/2_4_common_schema.adoc
Changed "varianbleKind" to "variableKind"
> Fixed typo in 2.4

- docs/2_2_common_mechanisms.adoc
- docs/2_4_common_schema.adoc
- docs/2_5_fmu_distribution.adoc
- docs/examples/co_simulation_early_return.xml
> Fixed typos

- docs/2_4_common_schema.adoc
> Added non-normative explanation for usage of stepSize in ME

- headers/fmi3FunctionTypes.h
Checklist
Hi!
By removing the trailing comma as highlighted in the changeset, then, the headers compile also as C89.
I am aware that the standard mentions that the headers are C99, however, I noticed that the other enum definitions below in the same file are written without trailing commas and therefore hopefully removing this one wouldn't be an issue.
> Removed trailing comma in fmi3FunctionTypes.h

- docs/2_2_common_mechanisms.adoc
> Clarify partial derivatives w.r.t. non-inputs
