modelica/fmi-standard

docs/3_1_model_exchange_math.adoc, docs/3_2_model_exchange_api.adoc
=> Fix #393 according to the suggestion in the ticket

.travis.yml
=> Check links only for 4xx errors in CI (#452)

docs/2_1_common_api.adoc, headers/fmi3FunctionTypes.h
As decided in the FMI Steering Committee Meeting on Nov 6, 2018
=> Remove variadic arguments from logger callback (#435)

docs/2_3_fmu_distribution.adoc
Please check that i have done this correctly
fix #411
=> fix #411 Expanded text on mandatory api functions

docs/3_2_model_exchange_api.adoc
=> Fix description of fmi2GetContinuousStates (#334)

docs/2_2_common_schema.adoc
=> Clarify that all units must be defined in UnitDefinitions (#337)

docs/2_1_common_api.adoc, docs/4_2_co-simulation_api.adoc, headers/fmi3FunctionTypes.h, headers/fmi3Functions.h
and remove fmi3StatusKind enum
=> Replace generic fmi3Get*Status with fmi3DoStep*Status functions

docs/examples/co_simulation.xml, docs/examples/model_exchange.xml, schema/fmi3AttributeGroups.xsd, schema/fmi3ModelDescription.xsd, schema/fmi3Variable.xsd
to simplify XML structure
see #514
=>  Change <ModelVariables> from composition to inheritance

CONTRIBUTING.adoc
=> Add “Adding and editing figures” section

schema/fmi3Annotation.xsd, schema/fmi3AttributeGroups.xsd, schema/fmi3ModelDescription.xsd, schema/fmi3Type.xsd, schema/fmi3Unit.xsd, schema/fmi3Variable.xsd, schema/fmi3VariableDependency.xsd
=> Remove documentation annotations from XSD files

docs/2_1_common_api.adoc
I only changed the link.
We might consider rewriting the text to use their suggested citing of their work. (see corresponding issue #564)
=> Fix link to ColPack library (#564)

.circleci/validate_xml.py, docs/2_2_common_schema.adoc, docs/examples/co_simulation.xml, docs/examples/model_exchange.xml, docs/examples/model_structure_example1.xml, docs/examples/model_structure_example2.xml, docs/examples/model_structure_example3.xml, docs/examples/unit_definition.xml
=> Move XML examples to separate files

docs/docinfo.html
=> Highlight current section in TOC

CONTRIBUTING.adoc
=> Update documentation of tags

docs/2_1_common_api.adoc
to build shared library
(see #420)
=> Clarify that a modified macro may be used

.circleci/validate_xml.py, docs/examples/co_simulation.xml, docs/examples/model_exchange.xml, docs/examples/model_structure_example1.xml, docs/examples/model_structure_example2.xml, docs/examples/model_structure_example3.xml, docs/examples/unit_definition.xml, docs/examples/variable_types.xml, schema/fmi3ModelDescription.xsd, schema/fmi3Type.xsd, schema/fmi3Variable.xsd, schema/fmi3VariableDependency.xsd
=> Use inheritance for TypeDefinitions and Unknowns

docs/2_1_common_api.adoc, docs/2_3_fmu_distribution.adoc, headers/fmi3FunctionTypes.h, headers/fmi3Functions.h, headers/fmi3PlatformTypes.h
to align with fmi3FunctionTypes.h
=> Rename fmi3TypesPlatform.h to fmi3PlatformTypes.h

docs/2_1_common_api.adoc, docs/3_2_model_exchange_api.adoc, docs/4_2_co-simulation_api.adoc, headers/fmi3FunctionTypes.h, headers/fmi3Functions.h
This pull request adds the missing enter and exit configuration function to header files and update the api docu. (as described in issue #595)
=> Add enter/exitConfigurationMode functions

schema/fmi3ModelDescription.xsd, schema/fmi3Type.xsd
=> Rename fmi3TypeDefintion to fmi3TypeDefinition

headers/fmi3FunctionTypes.h, headers/fmi3PlatformTypes.h
and fix argument name
see #620
=> Add fmi3Clock type

headers/fmi2FunctionTypes.h, headers/fmi2Functions.h, headers/fmi2TypesPlatform.h, schema/fmi2Annotation.xsd, schema/fmi2AttributeGroups.xsd, schema/fmi2ModelDescription.xsd, schema/fmi2ScalarVariable.xsd, schema/fmi2Type.xsd, schema/fmi2Unit.xsd, schema/fmi2VariableDependency.xsd
- correct documentation string regarding FMI verssion, see #388 
- Change copyright year to -2019
- Add FMI version in comment
=> Adapt xsd files and header files

.circleci/config.yml, CHANGELOG.md, CONTRIBUTING.adoc
=> Convert changelog to markdown

docs/examples/model_structure_example1.xml, docs/examples/model_structure_example2.xml, docs/examples/model_structure_example3.xml, docs/examples/unit_definition.xml, schema/fmi3FMUType.xsd, schema/fmi3ModelDescription.xsd
elements in the the XML schema and fix examples
see #660
=> Validate combinations of <ModelExchange> and <CoSimulation>

docs/2_2_common_schema.adoc
=> Add alpha tag note to fmiVersion attribute

docs/2_1_common_api.adoc, docs/5___literature.adoc
=> Add missing paragraph on graph coloring algorithms

docs/2_1_common_api.adoc
improve wording and fix formatting
see #712
=> Clarify access rules for variables,

.circleci/config.yml
=> Validate HTML only on master

docs/2_2_common_schema.adoc
and clarify that all variables in an alias set must have the same dimensions
=> Fix definition of "alias variable", add definition of "alias set",

docs/2_1_common_api.adoc
Much of the text has changed since the issue #659 originated.
However, I found a few typos and formatting issues that are fixed in this pull request.
=> Corrections related to #659

docs/0___preamble.adoc
according to discussion in #728
=> add abbreviations for FMI interface types 

docs/2_2_common_schema.adoc
This should be an easy merge, just a few spaces and single quotes
=> Fix minor formatting issues around '='

docs/2_1_common_api.adoc
... as FMI for PLM does not seem to exist any longer and is not use to my knowledge
solving #291 and #787
=> removing reserved fmi3 for FMI for PLM for fmuResourceLocation

docs/1___overview.adoc
- fixing formatting (minor change)
- reflecting the possibility to use other languages for source files and define them in the build configuration
=> Changing the requirment to use C

docs/2_1_common_api.adoc
- Unified variable names
- Clarifications
=> Fixes on partial derivatives

docs/4_2_co-simulation_api.adoc, docs/fmi-spec.css
This is a mostly empty table with the right state headings.
We need to fill it in.
Fixes #711
=> Added table for Scheduled Execution Simulation

docs/4_1_co-simulation_math.adoc
=> Clarify stepsize and discourage usage of CS for real sampled data systems but recommend HCS or SES instead

docs/0___preamble.adoc
clarifications to preamble SES is not only for controller code
=> clarifications to preamble

docs/2_1_common_api.adoc
Update 2_1_common_api with priority level non normative information
=> Update 2_1_common_api with priority level non normative information

docs/0___preamble.adoc
to avoid confusion, as we have an ODE interface in FMI 3.0 ME
=> remove reference to DAE

docs/2_2_common_schema.adoc, schema/fmi3Variable.xsd
=> Use UInt64 for dimension sizes

docs/2_1_common_api.adoc
=> Clarify logging according (#186)

docs/2_2_common_schema.adoc
This addresses unique annotations #629.
I need help with fixing the text in the image. A replacement text has been written in #629 .
=> Addresses unique annotations - #629

docs/4_2_basic_co-simulation_api.adoc
This is an attempt to simplify the fmi3discard description, see #630
=> FMI3Discard clarification - #630

docs/2_1_common_api.adoc
according to https://github.com/modelica/fmi-standard/issues/804
=> define nuemeric data type

docs/2_3_fmu_distribution.adoc
=> making resource directory mandatory

.circleci/validate_xml.py, docs/2_1_common_api.adoc, docs/2_2_common_schema.adoc, docs/examples/alias_example.xml, schema/fmi3Variable.xsd
=> Add <Alias> element to model variables

.circleci/validate_xml.py, docs/examples/co_simulation_early_return.xml
and fix co_simulation_early_return.xml
solves #839
=> Validate all XML examples

docs/2_2_common_schema.adoc
according to discussion in #387
=> add statement to explicitly forbid changes in the xml

docs/examples/alias_example.xml, docs/examples/build_configuration.xml, docs/examples/co_simulation.xml, docs/examples/co_simulation_early_return.xml, docs/examples/model_exchange.xml, docs/examples/model_structure_example1.xml, docs/examples/model_structure_example2.xml, docs/examples/model_structure_example3.xml, docs/examples/model_structure_example4.xml, docs/examples/unit_definition.xml
=> Change fmiVersion in examples to "3.0-alpha.3"

docs/4_3_basic_co-simulation_schema.adoc
=> Add description of attribute "fixedInternalStepSize"

docs/0___preamble.adoc, docs/index.adoc
=> Add feature matrix for FMI interfaces

docs/3_2_model_exchange_api.adoc, docs/examples/c-code/model_exchange.c
=> Fix super dense time

docs/2_4_common_co-simulation.adoc, docs/4_3_basic_co-simulation_schema.adoc, docs/5_2_hybrid_co-simulation_api.adoc, docs/5_3_hybrid_co-simulation_schema.adoc, docs/6_2_scheduled_co-simulation_api.adoc, docs/6_3_scheduled_co-simulation_schema.adoc
- canNotUseBasicCoSimulation
- providesHybridCoSimulation
- providesScheduledCoSimulation
#solves 884
=> Remove obsolete attributes from docs

docs/2_1_common_api.adoc
=> describe seed and sensitivity as components of seed and sensitivity

docs/0___preamble.adoc, docs/1___overview.adoc, docs/2_2_common_schema.adoc, docs/2_4_common_co-simulation.adoc, docs/8___appendix.adoc
Simple typos and formatting issues
=> Fmi3 typo fixes

docs/2_2_common_schema.adoc, docs/3_1_model_exchange_math.adoc, docs/4_2_basic_co-simulation_api.adoc
State machine modes must be formatted as *My Mode*.
I hope I found all...
=> Fix formatting of state machine modes

docs/2_1_common_api.adoc, docs/3_3_model_exchange_schema.adoc, docs/4_3_basic_co-simulation_schema.adoc, docs/examples/pseudo_code_co_simulation_intermediate_variable_access.txt, docs/examples/pseudo_code_co_simulation_scheduled_execution_simulation.txt, headers/fmi3FunctionTypes.h, schema/fmi3InterfaceType.xsd
- fmi3CallbackAllocateMemory
- fmi3CallbackFreeMemory
and attribute "canNotUseMemoryManagementFunctions"
see #122
=> Remove memory management functions

docs/1___overview.adoc
First attempt to a whats new section, please discuss tone and content.
=> Add Whats New

docs/examples/build_description_complex.xml, docs/examples/build_description_simple.xml, schema/fmi3BuildDescription.xsd, schema/fmi3TerminalsAndIcons.xsd
in buildDescription.xml and portsAndIcons.xml
=> Harmonize format of attribute "version"

docs/2_2_common_schema.adoc, docs/3_1_model_exchange_math.adoc, docs/3_2_model_exchange_api.adoc, docs/4_1_basic_co-simulation_math.adoc, docs/8___appendix.adoc
=> Fix dependent parameter

docs/1___overview.adoc
The overview table is incorrect partially. 
The formatting of the "except ..." parts is not perfect, perhaps someone has a better idea.
=> update overview table

docs/2_2_common_schema.adoc, docs/examples/structural_paramer_example.xml
fixing the second open point for #464
=> create example xml file for structural parameter

docs/2_1_common_api.adoc
(previously only ME was mentioned)
=> Describe fmi3ExitInitializationMode for all FMU types

docs/2_2_common_schema.adoc
as the current description contradicts parameter tuning and parameter propagation
=> Fix description of causality "parameter"

docs/2_2_common_schema.adoc
=> Improve model structure description

docs/2_3_fmu_distribution.adoc
=> Improve fmu distribution description

docs/2_4_common_co-simulation.adoc, docs/3_1_model_exchange_math.adoc, docs/3_2_model_exchange_api.adoc, docs/3_3_model_exchange_schema.adoc, docs/4_1_basic_co-simulation_math.adoc, docs/4_3_basic_co-simulation_schema.adoc, docs/6_2_scheduled_co-simulation_api.adoc
should be easy to review as only minor fixed.
=> Fix formatting issues from Review tickets #1011- #1023

docs/3_1_model_exchange_math.adoc, docs/8___appendix.adoc
=> Fixes for #1015

docs/6_2_scheduled_co-simulation_api.adoc
Fixes last remaining issue in #1023.
=> Add activation clock timing constraint

docs/5_2_hybrid_co-simulation_api.adoc, docs/8___appendix.adoc
Addresses most issues raised by #1022.
=> Fix issues of #1022

docs/2_1_common_api.adoc, docs/2_3_fmu_distribution.adoc
Resolves #1020 
and discussion in #814
=> Make resouces folder optional and describe return of NULL pointer

docs/3_2_model_exchange_api.adoc
=> Fix spelling of state Instantiated

docs/1___overview.adoc, docs/2_1_common_api.adoc, docs/3_2_model_exchange_api.adoc, headers/fmi3FunctionTypes.h
=> Turn nx to nStates etc

docs/2_2_common_schema.adoc, docs/2_3_fmu_distribution.adoc
=> Require reverse domain names for terminal names

docs/examples/alias_example.xml, docs/examples/co_simulation_early_return.xml, docs/examples/model_exchange.xml, docs/examples/model_structure_example1.xml, docs/examples/model_structure_example2.xml, docs/examples/model_structure_example3.xml, docs/examples/model_structure_example4.xml, docs/examples/structural_parameter_example.xml, docs/examples/variable_types.xml
I've made the minimal "obvious" changes here, but in some cases I may have changed the intent of the example unintentionally.  Please check!  But these are now "clean" according to my model.
=> Correct docs/examples for VDMCheck3

docs/2_2_common_schema.adoc
=> Improve explanation of inital value positive for structural parameters

docs/2_2_common_schema.adoc, docs/examples/co_simulation.xml, docs/examples/co_simulation_early_return.xml, docs/examples/model_exchange.xml
Update Modelica.SIunits of MSL v3.x.y to Modelica.Units.SI of MSL v4.0.0.
=> Update to MSL v4.0.0

docs/2_4_common_co-simulation.adoc, docs/4_1_basic_co-simulation_math.adoc, docs/4_2_basic_co-simulation_api.adoc, docs/4_3_basic_co-simulation_schema.adoc
=> Fixes in BCS description

docs/1___overview.adoc, docs/2_1_common_api.adoc, docs/2_2_common_schema.adoc, docs/3_1_model_exchange_math.adoc, docs/3_2_model_exchange_api.adoc, docs/5_2_hybrid_co-simulation_api.adoc, docs/8___appendix.adoc, headers/fmi3FunctionTypes.h
=> Remove parameter inputEvent from fmi3EnterEventMode()

docs/4_2_co-simulation_api.adoc
=> define calling sequence in intermediate update mode

docs/5_1_scheduled_execution_math.adoc, docs/5_2_scheduled_execution_api.adoc
I tried to improve the description for SE focusing on Intermediate Update Mode and Clock Activation Mode. @IZacharias @andreas-junghanns @t-sommer @clagms I would like to invite you to comment on this PR.
=> Some improvements on SE documentation

docs/4_2_co-simulation_api.adoc
=> disallow fmi3GetOutputDerivatives in Intermediate Update Mode

headers/fmi3PlatformTypes.h
=> Change typedef of fmi3Boolean from int to char

docs/2_2_common_schema.adoc
@masoud-najafi : This removal is, I think, in line with what we discussed and decided at a web design meeting. Please approve if you agree and I will merge.
=> Remove value restriction from XML

docs/2_2_common_schema.adoc
=> Remove incomplete enumeration of legal xs:double values

docs/2_1_common_api.adoc, docs/3_2_model_exchange_api.adoc, headers/fmi3FunctionTypes.h
Resolves #1016 
except for #1151 
Strangely, in https://github.com/modelica/fmi-standard/commit/5e2b4f47a9ebabd4499962df5535a9f524489829 I had to introduce a dummy Todo line to get correct formatting. Could someone familier with adoc please check?
=> Fixes to 3.2 (ME API)

docs/2_1_common_api.adoc, docs/2_2_common_schema.adoc
=> Clarify usage of local clocks

LICENSE.txt
=> Remove NonCommercial part

schema/fmi3InterfaceType.xsd, schema/fmi3ModelDescription.xsd
=> Add fmi3ScheduledExecution to schema

docs/1___overview.adoc
=> Remove misleading array indexing conventions

docs/0___preamble.adoc, docs/2_2_common_schema.adoc
Fixes #1197 
I will port this to https://github.com/modelica/fmi-design/blob/master/FMI_2.0.2/FunctionalMockupInterface_v2.0.2.docx once the PR got accepted
=> Clarify 0-based arrays

.circleci/config.yml, docs/X_layered_XCP.adoc
I broke the previous PR #1095.
=> Layered XCP

docs/2_5_fmu_distribution.adoc
=> Add code examples of all import methods

docs/1___overview.adoc
=> Update overview table regarding Intermdiate Update in SE

docs/1___overview.adoc, docs/2_1_common_math.adoc, docs/2_2_common_mechanisms.adoc, docs/2_3_common_states.adoc, docs/2_4_common_schema.adoc, docs/3_1_model_exchange_math.adoc, docs/7___appendix.adoc
Checklist
Add your [meaningful description](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#bug-reports) here and reference any related issues with `#<issue>`.
=> Replace signal with variable

docs/0___preamble.adoc, docs/2_2_common_schema.adoc, docs/2_3_fmu_distribution.adoc
Fixes #1207 
Shall be merged only after a vote in the Steering committe
=> Add /extra directory to 2.0.2

docs/2_2_common_mechanisms.adoc, docs/2_4_common_schema.adoc, docs/3_2_model_exchange_api.adoc, docs/4_2_co-simulation_api.adoc, docs/5_2_scheduled_execution_api.adoc
This PR should fix #1187 and partly #845 (the handling of string array variables is missing).
=> Serialization of array variables

docs/2_4_common_schema.adoc, docs/examples/unit_definition.xml, schema/fmi3Unit.xsd
and formulas in section "Definition of Units"
fixes #1220
=> Add inverse display units and improve text

docs/2_6_source_code.adoc
Hello, I tried to improve the description on how an importer shall choose the right BuildConfiguration for its platform. @IZacharias , @andreas-junghanns and everyone else interested please comment on this PR. Thanks.
=> Handle source code

docs/1___overview.adoc
~~If this gets accepted, we need to fix the text to reflect that we allow Intermediate Update Mode also in ME.~~
=> Fix ME feature entries

docs/2_4_common_schema.adoc
=> Correct so that relativeQuantity affects base units as well as DisplayUnits

docs/2_4_common_schema.adoc
Port addition from #1266 to FMI 3.0
=> Connections must have the same "relativeQuantity" attrribute on both sides

docs/2_4_common_schema.adoc
=> Disallow offset for inverse DisplayUnit

docs/2_3_fmu_distribution.adoc
=> clarify deflate in fmi 2.0.3, backport of #1291 

docs/2_5_fmu_distribution.adoc
=> Add platform tuple examples for shared libraries

docs/2_2_common_mechanisms.adoc
We have improved the text and suggest this to be sufficient, please re-read and comment.
=> Clarify v_rest and v_known

docs/3_1_model_exchange_math.adoc
=> mention event indicators in math description of initialization mode in FMI 2.0.3

docs/2_2_common_mechanisms.adoc, docs/2_3_common_states.adoc, headers/fmi3FunctionTypes.h
The xrefs for SetClock and GetClock pointed to a strange place - I found a slightly better place. If you can suggest an even better one, please do!
=> Improve xrefs for get/set clocks

docs/5___scheduled_execution.adoc
=> Change CS to SE in SE introduction

docs/2_2_common_mechanisms.adoc, docs/2_3_common_states.adoc, docs/4_2_co-simulation_api.adoc, headers/fmi3FunctionTypes.h
=> remove clocksAboutToTick from doStep()

docs/2_4_common_schema.adoc, docs/examples/string_vector_example.xml
This PR should fix the missing parts for string (array) start values mentioned in issue #843
=> String array start values

docs/2_3_common_states.adoc, docs/2_4_common_schema.adoc, docs/examples/structural_parameter_example.xml
This PR should clarify the question raised in issue #1293
=> Clarify structural parameters

docs/2_4_common_schema.adoc, docs/docinfo.html
resolves #1327 
Please review - yo are welcome to commit directly
=> Unify heading depth

docs/2_2_common_mechanisms.adoc
This is a small PR to fix https://github.com/modelica/fmi-standard/issues/1333
=> Fix https://github.com/modelica/fmi-standard/issues/1333

docs/2_4_common_schema.adoc
Fixes a small typo in the previous solution of https://github.com/modelica/fmi-standard/issues/1327.
Typo is described in https://github.com/modelica/fmi-standard/issues/1327#issuecomment-796598308
=> Fixes #1327

.circleci/config.yml, docs/index.adoc
=> Set revdate and revnumber in CI

headers/fmi3PlatformTypes.h
=> Use bool from stdbool.h instead of _Bool

headers/fmi3FunctionTypes.h
=> Remove explicit enum values from fmi3DependencyKind

.circleci/config.yml
=> Trigger CI for tags

docs/2_2_common_mechanisms.adoc, docs/2_3_common_states.adoc
This does not address the name of the argument (yet).
Should it be "clocksUpdated"?
=> Clarify clocksTicked description

docs/5_1_scheduled_execution_math.adoc, docs/5_2_scheduled_execution_api.adoc
@clagms @IZacharias this is hopefully a small fix. Would you please check if my adjustments are okay.? Thanks.
=> Remove Phrase 'global variable'

docs/1___overview.adoc
=> wording to not seemingly forbid external scheduling with CS

docs/7___appendix.adoc
=> glossary entry for event iteration

docs/4_4_co-simulation_schema.adoc
=> replace synchronous clocks by clocks in CS

docs/2_2_common_mechanisms.adoc, docs/2_4_common_schema.adoc, docs/examples/scheduled_execution.xml
=> Dependencies Variables and Clocks

docs/1___overview.adoc, docs/2_3_common_states.adoc, docs/2_5_fmu_distribution.adoc, docs/7___appendix.adoc
and improve language
fixes #1425
=> Change "FMI interface type" to "interface type"

docs/2_4_common_schema.adoc
Fixes https://github.com/modelica/fmi-standard/issues/1412
=> Clarifies the characteristics of the previous value

docs/examples/scheduled_execution.xml
Fix for Issue #1445 @IZacharias PLease review and merge.
=> Fix ScheduledExecution XML Description Example has no <ScheduledExecution> element

docs/2_4_common_schema.adoc
Fix https://github.com/modelica/fmi-standard/issues/1443
=> Variables dont share previous

docs/2_4_common_schema.adoc
Fixes https://github.com/modelica/fmi-standard/issues/1460
@andreas-junghanns , please double check description of the attribute.
=> Add maxSize attribute to the document.

.circleci/lint_docs.py, schema/fmi3Annotation.xsd, schema/fmi3AttributeGroups.xsd, schema/fmi3BuildDescription.xsd, schema/fmi3InterfaceType.xsd, schema/fmi3ModelDescription.xsd, schema/fmi3Terminal.xsd, schema/fmi3TerminalsAndIcons.xsd, schema/fmi3Type.xsd, schema/fmi3Unit.xsd, schema/fmi3Variable.xsd, schema/fmi3VariableDependency.xsd
Adds headers and XSD files to the set of files being linted, removes tabs from XSDs. Resolves #1464.
=> Enable linting of headers and XSDs (#1464)

docs/2_4_common_schema.adoc
=> replace rigorous

docs/2_4_common_schema.adoc
=> remove redundancy for start value

docs/2_3_fmu_distribution.adoc
and introduce documentation/externalDependencies.{txt|html}
fixes #1486
=> Relax requirement for including dependencies

docs/2_2_common_mechanisms.adoc, docs/2_3_common_states.adoc, docs/5_1_scheduled_execution_math.adoc
Added a new paragraph to clarify that and xref a few stray callback references.
=> Clarify no callback in callback

docs/2_3_common_states.adoc
=> Remove obsolete ban to change callback functions

docs/2_5_fmu_distribution.adoc
=> Consolidate i386, i586, and i686 into x86

docs/2_5_fmu_distribution.adoc
=> Remove static linking details from platform tuple

docs/2_2_common_mechanisms.adoc, docs/2_4_common_schema.adoc
=> Clarify value of the independent variable

docs/2_4_common_schema.adoc
Sorted constraints for previous attribute and added Clock as exception.
=> Add previous constraint for Clocks #1444

docs/2_3_common_states.adoc, headers/fmi3FunctionTypes.h
=> Remove argument "instanceName" from fmi3CallbackLogMessage

docs/2_2_common_mechanisms.adoc
=> Clarify that headers are C99

docs/1___overview.adoc, docs/2_2_common_mechanisms.adoc, docs/2_3_common_states.adoc, docs/2_4_common_schema.adoc, docs/5_1_scheduled_execution_math.adoc, docs/5_2_scheduled_execution_api.adoc, docs/5_3_scheduled_execution_example.adoc, docs/5_4_scheduled_execution_schema.adoc, docs/5___scheduled_execution.adoc, docs/7___appendix.adoc, docs/examples/snippets.c
As discussed in a recent design meeting and in issue #1543, this is a draft pr with comments about the current description of Scheduled Execution.
=> Remarks about Scheduled Execution

docs/1___overview.adoc, docs/7___appendix.adoc
Minor changes in "How to read this document" and definition of "FMI"
=> fixed parentheses

docs/2_5_fmu_distribution.adoc
Everyone is welcome to review.
=> explicit fmi3 header not in FMU

docs/1___overview.adoc
=> Clarify formatting of RFC 2119 keywords

docs/2_2_common_mechanisms.adoc
@andreas-junghanns you may also forward my invite to review this small addition to the specification. Thank you.
FYI @PTaeuberDS
=> Do not change global settings which affect other processes/threads on preemptive systems

docs/2_5_fmu_distribution.adoc
=> Explicitly allow additional entrypoints

.circleci/config.yml
=> Explicitly set machine image in CI

docs/2_4_common_schema.adoc
=> Allow multiple BuildConfigurations for the same platform

headers/fmi3FunctionTypes.h
=> Switch position of fmi3EventTrue and fmi3EventFalse

headers/fmi3Functions.h
=> Declare fmi3SetShift{Decimal|Fraction}

docs/examples/scheduled_execution.xml
@andreas-junghanns would you please check. I changed:
* Undo parts of #1691.
* Format the xml so it looks nice when inserted into the spec.
=> Remove supportsFraction from SE example

docs/0___preamble.adoc, docs/2_3_common_states.adoc, docs/2_4_common_schema.adoc, docs/2_5_fmu_distribution.adoc, docs/2_6_versioning_layered_standards.adoc, docs/3_1_model_exchange_math.adoc, docs/3_2_model_exchange_api.adoc, docs/3___model_exchange.adoc, docs/4_1_co-simulation_math.adoc, docs/4_4_co-simulation_schema.adoc, docs/4___co-simulation.adoc
No known API or functional changes added - please check.
=> Rewriting 2.5 and 2.6

docs/3_2_model_exchange_api.adoc, docs/3_4_model_exchange_schema.adoc, docs/4_1_co-simulation_math.adoc, docs/4_2_co-simulation_api.adoc, docs/4_4_co-simulation_schema.adoc, docs/5_4_scheduled_execution_schema.adoc, docs/examples/alias_example.xml, docs/examples/co_simulation.xml, docs/examples/co_simulation_early_return.xml, docs/examples/model_exchange.xml, docs/examples/model_structure_example1.xml, docs/examples/model_structure_example2.xml, docs/examples/model_structure_example3.xml, docs/examples/model_structure_example4.xml, docs/examples/string_vector_example.xml, docs/examples/structural_parameter_example.xml, docs/examples/unit_definition.xml
@nickbattle : please check the addition requirement for `providesIntermediateUpdate` in connection with `canReturnEarlyAfterIntermediateUpdate`.
=> Fix language from 4.2 to 4.4

docs/1___overview.adoc
@andreas-junghanns following https://github.com/modelica/fmi-standard/pull/1585 I updated "Table 1. Non-normative overview of features per interface type.". What do you think?
=> Intermediate Update/ clock Update in table overview of features per interface type

docs/2_4_common_schema.adoc
=> Fix type mappings in table 10

docs/examples/scheduled_execution.xml
As a first step initiated by #1721 I added dependency information w.r.t. the clocks in order to make the SE xml consistent.
=> add dependencies in SE xml

docs/2_2_common_mechanisms.adoc, docs/2_4_common_schema.adoc
Please check the last part, non normative text, rewrote it a bit.
Even if we want to be as short as possible it could be good that there is no misunderstanding as we ourselves managed to misunderstand it some one new is much more likely to do it
so I think its good we have something there to be more explicit, but if you really don't agree I can remove it
=> Remove most changes in 1706, change some parts

docs/2_4_common_schema.adoc
on platforms that support shared libraries
see also https://github.com/modelica/Reference-FMUs/issues/215
=> Discourage static linking

docs/2_2_common_mechanisms.adoc, docs/2_3_common_states.adoc, docs/3_2_model_exchange_api.adoc, docs/3___model_exchange.adoc, docs/6___literature.adoc
Checklist
Add your [meaningful description](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#bug-reports) here and reference any related issues with `#<issue>`.
=> Fix some typos

docs/5_1_scheduled_execution_math.adoc
More detailed content has been moved to the IG (see modelica/fmi-guides#35).
=> Reduce non-normative section on preemption due to IG

docs/5_2_scheduled_execution_api.adoc
=> Remove reference to deleted non-normative SE example

docs/2_3_common_states.adoc, docs/3_2_model_exchange_api.adoc, docs/4_2_co-simulation_api.adoc, docs/examples/snippets.c, headers/fmi3FunctionTypes.h
=> Remove parameters from fmi3EnterEventMode()

docs/7___appendix.adoc
Funding form BPIFrance and Region Ile de France
=> Added funding thanks to contributors

docs/2_4_common_schema.adoc, docs/2_5_fmu_distribution.adoc
resolves #1749 according to feedback by @GallLeo .
=> clarify domain usage

docs/2_2_common_mechanisms.adoc
=> Change A to J

docs/2_2_common_schema.adoc
back-ports #1122 to FMI 2.0
fixes #1784
=> Fix description of forbidden special values for real values in FMI 2.0.x

docs/2_3_fmu_distribution.adoc, schema/fmi3TerminalsAndIcons.xsd
=> Back-port terminalsAndIcons.xml to FMI 2.0

docs/3_2_model_exchange_api.adoc
Fixes #1629 
Has to be backported to Word --> #1778 
@GarronFish:  please check
=> Fix pseudocode example according to Karl's suggestion

.github/workflows/build-spec.yml, docs/4_3_co-simulation_example.adoc, docs/examples/snippets.c
=> Move "connected FMUs" example to snippets.c

docs/2_4_common_schema.adoc, generate_figures.ps1
=> Replace fmi3AbstractVariable figure w/ fmi3ArrayableVariable

docs/2_4_common_schema.adoc
=> Added description of the fmiBuildDescription element

docs/2_4_common_schema.adoc
=> Clarification of 'nominal' for array variables

.github/workflows/build-spec.yml
Checklist
Add your [meaningful description](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#bug-reports) here and reference any related issues with `#<issue>`.
=> Add REVNUMBER environment variable

docs/7___appendix.adoc
=> clarify usage of structural parameters in glossary

README.adoc
=> Add links to layered standards to readme

docs/index.adoc
Resolves #1860 
(and contributes to #1823)
=> add section links

docs/2_5_fmu_distribution.adoc
=> Require implementation of all API functions

docs/2_4_common_schema.adoc
=> Fix formatting of variableNamingConvention attribute

docs/6___appendix.adoc
See https://github.com/modelica/fmi-standard/issues/86#issuecomment-430365254
Checklist
=> Remove misinformation

docs/examples/snippets.c
This is just a very small cosmetic change
=> Unify snippet comment with rest of standard

schema/fmi3AttributeGroups.xsd
=> Correct types for decimal clock interval/shift

LICENSE.txt
=> Fix text of CC-BY-SA license in LICENSE.txt

docs/2_3_common_states.adoc, docs/3_2_model_exchange_api.adoc, docs/4_2_co-simulation_api.adoc
=> Remove requirement to call fmi3Terminate when terminateSimulation = fmi3True

docs/3_2_model_exchange_api.adoc
=> Remove requirement to to call fmi2Terminate

docs/0___preamble.adoc, docs/1___overview.adoc, docs/2_1_common_math.adoc
=> Fixed some spelling mistakes and inconsistent mathematical notations

docs/2_4_common_schema.adoc, docs/2_5_fmu_distribution.adoc, docs/2_6_versioning_layered_standards.adoc, docs/7___appendix.adoc
=> Fixed up asciidoc warnings

docs/1___overview.adoc
=> Updated documentation on patch releases

README.adoc
=> Add link to LS-REF to README.adoc

.github/workflows/build-spec.yml
To get rid of errors 
https://github.com/chrbertsch/fmi-standard/actions/runs/15041131969
=> fix ubuntu version in build
